config/routes.rb
Scriptverwaltung::Application.routes.draw do
  root :to => "scripts#index"
  resources :comments, only: [:create, :destroy]

  get "users/:id" => "users#show", as: "show_user"
  get "users/:id/toggle_admin" => "users#toggle_admin", as: "toggle_admin"

  match "/auth/:provider/callback", :to => "sessions#create"
  match "/auth/failure", :to => "sessions#failure"

  resources :scripts
  get "scripts/:id/download" => "scripts#download", as: "download_script"
  get "scripts/:id/comment" => "comments#new", as: "comment_script"
  get "scripts/:id/makeactiv" => "scripts#activate", as: "activate_script"

  get   "login" => "sessions#new", as: "login"
  delete "logout" => "sessions#destroy", as: "logout"

end

app/models/script.rb
class Script < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  attr_accessible :beschreibung, :dozent, :erscheinungsdatum, :fachrichtung, :hochschule, :kurs, :name, :upload
  validates :beschreibung, :dozent, :erscheinungsdatum, :fachrichtung, :hochschule, :kurs, :name, presence: true

  #Teilweise entnommen aus http://railscasts.com/episodes/134-paperclip
  has_attached_file :upload,
                    path: ":rails_root/uploaded_scripts/:id-:basename.:extension"

  validates_attachment_presence :upload
  validates_attachment_size :upload, less_than: 25.megabytes
  validates_attachment_content_type :upload, content_type: ['application/pdf', 'application/x-pdf', 'application/binary']   #Kleiner Workaround für den FF, der schickt pdf mit application/binary unter Linux
  validates_format_of :upload_file_name, with: %r{\.(pdf)$}i #Validierung des Dateinamen wegen des Workarounds.

  searchable do
    text :beschreibung, :dozent, :fachrichtung, :hochschule, :kurs, :name
  end

  def average_mark
    comments = self.comments
    unless comments.empty?
      sum = 0.0
      self.comments.each do |comment|
        sum += comment.mark
      end
      sum /= comments.count
    end
    sum
  end
end

app/controllers/scripts_controller.rb
#Encoding: utf-8
class ScriptsController < ApplicationController
  before_filter :require_login!, :except => [ :show, :index, :download ]
  before_filter :only_owner!, :only => [:edit, :update, :destroy]
  before_filter :isVisible?, :only => [:show]
  # GET /scripts
  # GET /scripts.json

  def index
    @search = Script.search do
      fulltext params[:search], minimum_match: 1
      paginate page: params[:page], per_page: 15
    end
    @scripts = @search.results
    store_return_url
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scripts }
    end
  end

  # GET /scripts/1
  # GET /scripts/1.json
  def show
    @script = Script.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @script }
      end
  end

  # GET /scripts/new
  # GET /scripts/new.json
  def new
    @script = Script.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @script }
    end
  end

  # GET /scripts/1/edit
  def edit
    @script = Script.find(params[:id])
  end

  # POST /scripts
  # POST /scripts.json
  def create
    @script = Script.new(params[:script])
    @script.user= User.find(session[:user_id])
    respond_to do |format|
      if @script.save
        format.html { redirect_to @script, notice: 'Script wurde angelegt' }
        format.json { render json: @script, status: :created, location: @script }
        sentMailToAdmins
      else
        format.html { render action: "new" }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scripts/1
  # PUT /scripts/1.json
  def update
    @script = Script.find(params[:id])
      respond_to do |format|
        if @script.update_attributes(params[:script])
          format.html { redirect_to @script, notice: 'Script wurde geändert.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @script.errors, status: :unprocessable_entity }
        end
      end
  end


  # DELETE /scripts/1
  # DELETE /scripts/1.json
  def destroy
    @script = Script.find(params[:id])
        @script.destroy
        respond_to do |format|
          format.html { redirect_to scripts_url }
          format.json { head :no_content }
        end
  end

  def download
    if script_activated?
      @script = Script.find(params[:id])
      send_file @script.upload.path , content_type:  @script.upload.content_type
    else
      redirect_to scripts_path, alert: "Das Script ist noch nicht freigeschaltet oder existiert nicht"
    end
  end

  def activate
    if isAdmin?
      @script = Script.find(params[:id])
      @script.activated= true
      @script.save
    end
    redirect_back_or_default(show_user_path(current_user))
  end

  private
    def script_activated?
      @script = Script.find(params[:id])
      unless @script.nil?
        return (isOwner?(@script) or isAdmin? or isActiv?(@script) )
      end
      false
    end

    def getHostUrl
      return "http://#{request.host}:#{request.port.to_s}"
    end

    def sentMailToAdmins
      admins = User.all.select do |admin|
        admin if admin.isAdmin
      end
      admins.each do |admin|
        begin
          AdminMailer.notification_email(admin,@script,getHostUrl).deliver
        rescue Exception
          #do nothing
        end
      end
    end
end

app/helpers/scripts_helper.rb
#encoding: utf-8
module ScriptsHelper
  #komplett übernommen aus http://stackoverflow.com/questions/2143300/protecting-the-content-of-public-in-a-rails-app
  def send_file(filepath, options = {})
    options[:content_type] ||= "application/force-download"
    response.headers['Content-Type'] = options[:content_type]
    response.headers['Content-Disposition'] = "attachment; filename=\"#{File.basename(filepath)}\""
    response.headers['X-Sendfile'] = filepath
    response.headers['Content-length'] = File.size(filepath)
    render nothing: true
  end
end

app/views/scripts/_comment.html.erb
<h3>Bewertungen</h3>
<br>
<br>
<br>
<h4>Durschnittliche Bewertungen:</h4>
<%= @script.average_mark %>
<br>
<br>
<br>
<% @script.comments.each do |comment| %>
    <p>Note: <%= comment.mark %> User: <%= link_to(comment.user.username, show_user_path(comment.user), class: "btn") %>
    	<%= link_to('Löschen', comment, method: :delete, confirm: 'Bist du sicher?', class: "btn btn-mini btn-danger") if isAdmin? or isOwner?(comment) %> </p>
    <%= comment.content %>
    <hr>
<% end %>

<%= link_to 'Script bewerten', comment_script_path(@script), class: "btn btn-mini" %>

app/views/scripts/_form.html.erb
<%= form_for(@script, :html => { :multipart => true }) do |f| %>
  <%= render partial: 'shared/error', locals: {entity: @script, text: "dieses Script" } %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dozent %><br />
    <%= f.text_field :dozent %>
  </div>
  <div class="field">
    <%= f.label :kurs %><br />
    <%= f.text_field :kurs %>
  </div>
  <div class="field">
    <%= f.label :fachrichtung %><br />
    <%= f.text_field :fachrichtung %>
  </div>
  <div class="field">
    <%= f.label :hochschule %><br />
    <%= f.text_field :hochschule %>
  </div>
  <div class="field">
    <%= f.label :beschreibung %><br />
    <%= f.text_area :beschreibung %>
  </div>
  <div class="field">
    <%= f.label :erscheinungsdatum %><br />
    <%= f.date_select :erscheinungsdatum, start_year: Time.now.year - 10, end_year: Time.now.year + 1 %>
    <br>
    <%= f.file_field :upload %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Show', @script, class: "btn btn-mini" %>
<%= link_to 'Back', scripts_path, class: "btn btn-mini" %>

app/views/scripts/_index_buttons.html.erb
<%= link_to('Edit', edit_script_path(script), class: "btn btn-mini") if isAdmin? or !isActiv?(script) %>
<%= link_to('Destroy', script, method: :delete, confirm: 'Are you sure?', class: "btn btn-mini btn-danger") if isAdmin? or !isActiv?(script) %>
<%= link_to('Freigeben', activate_script_path(script), confirm: 'Are you sure?', class: "btn btn-mini btn-success") if isAdmin? and !isActiv?(script) %>

app/views/scripts/edit.html.erb
<h1>Script bearbeiten</h1>

<%= render 'form' %>

app/views/scripts/index.html.erb
<h1>Auflistung aller Scripts</h1>
<br>

<%= render partial: 'shared/listings', locals: {scripts: @scripts} %>
<%= paginate @scripts %>
<%= link_to 'New Script', new_script_path, class: "btn btn-mini btn-info" %>

app/views/scripts/new.html.erb
<h1>Neues Script</h1>

<%= render 'form' %>

app/views/scripts/show.html.erb
<%= render partial: 'shared/script' %>

<p><%= link_to "Download", download_script_path(@script), class: "btn btn-mini btn-info" %></p>

<%= render partial: 'scripts/index_buttons', locals: {script: @script} %>


<br>
<br>

<%= render 'comment' %>