config/routes.rb
Scriptverwaltung::Application.routes.draw do
  root :to => "scripts#index"
  resources :comments, only: [:create, :destroy]

  get "users/:id" => "users#show", as: "show_user"
  get "users/:id/toggle_admin" => "users#toggle_admin", as: "toggle_admin"

  match "/auth/:provider/callback", :to => "sessions#create"
  match "/auth/failure", :to => "sessions#failure"

  resources :scripts
  get "scripts/:id/download" => "scripts#download", as: "download_script"
  get "scripts/:id/comment" => "comments#new", as: "comment_script"
  get "scripts/:id/makeactiv" => "scripts#activate", as: "activate_script"

  get   "login" => "sessions#new", as: "login"
  delete "logout" => "sessions#destroy", as: "logout"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :username

  has_many :authorizations
  has_many :scripts
  has_many :comments

  validates :username, :email, presence: true

  #http://net.tutsplus.com/tutorials/ruby/how-to-use-omniauth-to-authenticate-your-users/ Teil 7
  def add_new_provider auth_hash
    unless authorizations.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
      Authorization.create user: self, provider: auth_hash["provider"], uid: auth_hash["uid"]
    end
  end


  def self.findOrCreateNewUserWithProvider auth_hash
    auth = Authorization.find_by_uid_and_provider(auth_hash['uid'],auth_hash['provider'])
    if auth
      #gefunden
      return auth.user
    else
      #neu anlegen da noch nie eingeloggt
      if auth_hash['provider']['cas']
        user = User.new username: auth_hash["extra"]["user"], email: auth_hash["extra"]["attributes"][0]["mail"]
      elsif auth_hash['provider']['identity']
        user = User.new username: Identity.find(auth_hash["uid"]).username, email: auth_hash["info"]["email"]
      end
      user.add_new_provider auth_hash
      user.save
      user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :admin?, :only => [ :toggle_admin ]
  before_filter :require_login!, :except => [ :show ]
  def show
    @user = User.find(params[:id])
    store_return_url
  end

  def toggle_admin
  	User.find(params[:id]).toggle(:isAdmin).save
  	redirect_to show_user_path(current_user)
  end

  private
    def admin?
      unless isAdmin?
        redirect_to scripts_path, alert: "Sie haben keine Berechtigung zum Aufruf dieser Ressource "
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_listing_not_activ.html.erb
<br>
<table class="table table-striped table-bordered table-condesed">
  <tr>
    <th>Name</th>
    <th>Dozent</th>
    <th>Kurs</th>
    <th>Fachrichtung</th>
    <th>Hochschule</th>
    <th>Erscheinungsdatum</th>
    <th></th>

  </tr>

<% scripts.each do |script| %>
    <% unless isActiv?(script)%>
        <tr>
            <td><%= script.name %></td>
            <td><%= script.dozent %></td>
            <td><%= script.kurs %></td>
            <td><%= script.fachrichtung %></td>
            <td><%= script.hochschule %></td>
            <td><%= script.erscheinungsdatum %></td>
            <td>
                <p>
                    <%= link_to "Donwload", download_script_path(script), class: "btn btn-mini btn-info" %>
                    <%= link_to 'Show', script, class: "btn btn-mini btn-info" %>
                </p>
                <%= render partial: 'scripts/index_buttons', locals: {script: script} %>
            </td>
        </tr>
    <% end %>
<% end %>
</table>
<br />

app/views/users/_userList.html.erb
<br>
<table class="table table-striped table-bordered table-condesed">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>E-Mail</th>
    <th>Admin</th>
    <th></th>

  </tr>

<% users.each do |user| %>
        <tr>
            <td><%= user.id %></td>
            <td><%= user.username %></td>
            <td><%= user.email %></td>
            <td><% if user.isAdmin %>
                    <%= "ja" %>
                 <% else %>
                    <%= "nein" %>
                  <% end %>
               </td>
            <td>
                <p> <% unless user == current_user %>
                        <% if user.isAdmin %>
                            <%= link_to "Admin nehmen", toggle_admin_path(user), confirm: 'Rechte Nehmen?', class: "btn btn-mini btn-danger" %>
                        <% else %>
                            <%= link_to 'Admin geben', toggle_admin_path(user), confirm: 'Rechte geben?',class: "btn btn-mini btn-success" %>
                        <% end %>
                    <% end %>
                </p>
            </td>
        </tr>
<% end %>
</table>
<br />

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/show.html.erb
<div class="span1">&nbsp;</div>
 	<div class="span12">
		<h1>Userprofil von <%= @user.username %> </h1>
		<p>Username: <%= @user.username %> </p>
		<% if user_signed_in? and @user.id.eql? session[:user_id] #mache den nachfolgenden Content nur den den eigenen User sichtbar %>
				<p>Haupt-email: <%= @user.email %></p>
				<br><br>
    			<h3>Registrierte Authentifizierungsservices </h3>
    			<% @user.authorizations.each do |auth|%>
        			<p>
        				<%= auth.provider.to_s + " (uid: " + auth.uid + ")"  %>
        			</p>
    			<% end %>	
		 <% end %>
	  <br>
	  <h3>Uploads </h3>
	 <%= render partial: 'shared/listings', locals: {scripts: @user.scripts} %>
	  <br>
	  <% if isAdmin? and current_user.eql? @user %>
	  	<h3>Nicht Active Uploads</h3>
	 	<%= render partial: 'listing_not_activ', locals: {scripts: Script.all} %>
	 	<h3>User-Verwaltung</h3>
	 	<%= render partial: 'userList', locals: {users: User.all} %>
	 <% end %>
</div>