config/routes.rb
Scriptverwaltung::Application.routes.draw do
  root :to => "scripts#index"
  resources :comments, only: [:create, :destroy]

  get "users/:id" => "users#show", as: "show_user"
  get "users/:id/toggle_admin" => "users#toggle_admin", as: "toggle_admin"

  match "/auth/:provider/callback", :to => "sessions#create"
  match "/auth/failure", :to => "sessions#failure"

  resources :scripts
  get "scripts/:id/download" => "scripts#download", as: "download_script"
  get "scripts/:id/comment" => "comments#new", as: "comment_script"
  get "scripts/:id/makeactiv" => "scripts#activate", as: "activate_script"

  get   "login" => "sessions#new", as: "login"
  delete "logout" => "sessions#destroy", as: "logout"

end

app/views/shared/_error.html.erb
<% if entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= entity.errors.count %> Fehler verhindern, dass <%= text %>  gespeichert werden kann:</h2>
      <ul>
        <% entity.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_listings.html.erb
<table class="table table-striped table-bordered table-condesed">
  <tr>
    <th>Name</th>
    <th>Dozent</th>
    <th>Kurs</th>
    <th>Fachrichtung</th>
    <th>Hochschule</th>
    <th>Erscheinungsdatum</th>
    <th></th>

  </tr>

<% scripts.each do |script| %>
    <% if isActiv?(script) or isOwner?(script) or isAdmin? %>
        <tr>
            <td><%= script.name %></td>
            <td><%= script.dozent %></td>
            <td><%= script.kurs %></td>
            <td><%= script.fachrichtung %></td>
            <td><%= script.hochschule %></td>
            <td><%= script.erscheinungsdatum %></td>
            <td>
                <p>
                    <%= link_to "Donwload", download_script_path(script), class: "btn btn-mini btn-info" %>
                    <%= link_to 'Show', script, class: "btn btn-mini btn" %>
                </p>
                <%= render partial: 'scripts/index_buttons', locals: {script: script} %>
            </td>
        </tr>
    <% end %>
<% end %>
</table>

app/views/shared/_navbar.html.erb
<div class="page-header">
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container" >
        <div class="row">
          <div class="span4"><a class="brand" href="<%= scripts_path %>">Scriptverwaltung</a></div>
            <div class="pull-right">
              <% if user_signed_in? %>
                <%= link_to current_user.username , show_user_path(current_user), class: "btn btn-mini btn-info" %>
                <%= link_to "Logout" , logout_path, class: "btn btn-mini btn-danger", method: :delete  %>
              <% else %>
                <%= link_to "Login", login_path, class: "btn btn-mini btn-info" %>
              <% end %>
            </div>
            <%= form_tag scripts_path, class: "navbar-search pull-right", method: 'get' do %>
              <%= text_field_tag :search, params[:search], class: "search-query", placeholder: "Search"  %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_script.html.erb
<p>
<b>Name:</b>
<%= @script.name %>
</p>

<p>
  <b>Dozent:</b>
  <%= @script.dozent %>
</p>

<p>
  <b>Kurs:</b>
  <%= @script.kurs %>
</p>

<p>
  <b>Fachrichtung:</b>
  <%= @script.fachrichtung %>
</p>

<p>
  <b>Hochschule:</b>
  <%= @script.hochschule %>
</p>

<p>
  <b>Beschreibung:</b>
  <%= @script.beschreibung %>
</p>

<p>
  <b>Erscheinungsdatum:</b>
  <%= @script.erscheinungsdatum %>
</p>